task :default => :test

def files
  n = ENV["N"]
  f = (n && "ch%02d.rkt" % n.to_i) || ENV["F"] || "ch*.rkt"
end

task :test do
  sh "time raco test --direct #{files}"
end

task :reason do
  sh "time raco test --direct ch2*.rkt"
end

task :slow do
  sh "time raco test #{files}"
end

task :run do
  sh "time raco test #{files}"
end

task :cov do
  sh "raco cover #{files}"
end

task :clean do
  rm_f Dir["*~"]
end

task :sync do
  whereami = File.basename Dir.pwd

  if whereami == "zenspider" then
    sh "rsync -avP --existing ../../zenspider/schemers/little-schemer/ ."
  end
end
